# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI-CD

on:
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env: 
      LineToken: ${{ secrets.TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: |
          npm test
          shell: bash
          working-directory: LineNotifyServiceFastify
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v1
    -   # build image
      run: |
          docker info
          docker build -t linenotification -f Dockerfile .
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'intergoldlinenotification' }}
    
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        docker tag linenotification registry.heroku.com/$APP_NAME/web
        docker push registry.heroku.com/$APP_NAME/web                
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku container:release web -a $APP_NAME
